recipe: default.v1
language: pt

# ----------------------------------------------------------
# NLU PIPELINE OTIMIZADO
# ----------------------------------------------------------
pipeline:
  - name: WhitespaceTokenizer
    case_sensitive: false

  - name: RegexFeaturizer
    use_lookup_tables: true
    use_regexes: true

  - name: LexicalSyntacticFeaturizer

  - name: CountVectorsFeaturizer

  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true
    use_lookup_tables: true     # 🔥 IMPORTANTE
    entity_recognition: true    # 🔥 IMPORTANTE
    use_regexes: true

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1


# ----------------------------------------------------------
# POLICIES
# ----------------------------------------------------------
policies:
  - name: RulePolicy
    core_fallback_threshold: 0.80
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true


# ----------------------------------------------------------
# SERVER/BACKEND CONFIG
# ----------------------------------------------------------
url: "http://localhost:8000"
assistant_id: 20231002-151022-serious-space
